services:
   
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  ft:
    container_name: FT
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      context: .
    command: behave test/functional/features
   